# Generated by Django 5.2 on 2025-05-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_order_id_order_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='order_complete',
        ),
    ]
