# Generated by Django 5.2 on 2025-05-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_ordered_order_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
