# Generated by Django 5.2 on 2025-05-03 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
